FROM golang:1.24.0-alpine3.21 AS build
RUN apk add make && apk add build-base


WORKDIR /api

COPY . .

RUN make build

FROM alpine:latest

WORKDIR /api
COPY --from=build /api/xkcd .
COPY  config.yaml .
COPY  stopwords.txt .
EXPOSE 8080

ENTRYPOINT ["./xkcd"]